# Settings in the [build] context are global and are applied to all contexts 
# unless otherwise overridden by more specific contexts.
[build]
  # This is the directory to change to in the project before starting a build.
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  base = "/"

  # This is the directory that you are publishing from (relative to the 
  # root of your repo). I.e. where the deploy files will be copied from.
  publish = "public"


# Production context: All deploys from the Production branch set in your site's 
# deploy settings will inherit these settings.
[context.production]

  # The build command
  command = "yarn run build --prefix-paths && cp -r /build/ . && rmdir build"


# Deploy Preview context: All Deploy Previews will inherit these settings.
[context.deploy-preview]

  # The build command
  command = "yarn run build"

# Deploy Branch context: All deploys for the "test" branch will inherit these settings.
[context.test]

  # The build command
  command = "yarn run build --prefix-paths && cp -r /build/ . && rmdir build"