# Because Netlify now adds a folder to match the pathPrefix,
# we need to route to it correctly.
[[redirects]]
  from = "/*"
  to = "/blog/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/"
  to = "/blog/"
  status = 200
  force = true